### PR TITLE
[WIFI-2882] Add: image build workflow

### PR DESCRIPTION
**Pull request by dunaev-opsfleet**

### CODE REVIEW

**Comment by brennerm** [comment]
@dunaev-opsfleet Think we should also delete the image/tag when a PR is being closed. Otherwise we'll end up with a huge pile of PR tags that no one needs.

**Comment by dunaev-opsfleet** [comment]
@brennerm sure, we could do that using https://jfrog.com/knowledge-base/how-to-clean-up-old-docker-images/ with changed request using https://www.jfrog.com/confluence/display/JFROG/Artifactory+Query+Language . Should we go with that and make a Python script for cleaning up feature-branch images?
The only consirn I have is that we would still have SHA based images anyway

**Comment by brennerm** [comment]
@dunaev-opsfleet Actually I was thinking about something like this. :)
https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/master/.github/workflows/cleanup.yml

**Comment by oblom0v** [comment]
Just a short notice: I made a slight change to the workflow to also cleanup branch names with slashes:
https://github.com/Telecominfraproject/wlan-cloud-ucentralgw/blob/WIFI-2044-ucentralgw-pr-flow/.github/workflows/cleanup.yml

**Comment by dunaev-opsfleet** [comment]
@brennerm @oblom0v Thanks for help, almost started building the same thing once again :smile: 
Does it look good now?

**Review by brennerm — APPROVED** [review]

**Review by oblom0v — APPROVED** [review]

**Pull request merged**
